language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost-regex-dev

before_script:
    - uname -a
    - printenv

script:
  - cmake .
  - make
